version: "3.9"

services:
  mikhmon-old:
    image: php:8.1-apache
    container_name: mikhmon-old
    volumes:
      - ./mikhmon-old:/var/www/html
    networks:
      - app-network

  mikhmon-new:
    image: php:8.1-apache
    container_name: mikhmon-new
    volumes:
      - ./mikhmon-new:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
